/*
 * Site catalog. Everything the home page shows comes from this file.
 *
 * To hide a game: set `hidden: true` on its entry.
 * To feature a game in the "Hot right now" row: set `hot: true`.
 * Plain script (not JSON) so the site also works when opened from a folder.
 */
window.SITE = {
  name: 'Recess Arcade',
  tagline: 'Free games for awesome students 🎉'
};

window.CATEGORIES = [
  { id: 'running', label: 'Running', icon: '🏃' },
  { id: 'racing', label: 'Racing', icon: '🏎️' },
  { id: 'two-player', label: '2 Players', icon: '👯' },
  { id: 'sports', label: 'Sports', icon: '🏀' },
  { id: 'puzzle', label: 'Puzzle', icon: '🧩' },
  { id: 'arcade', label: 'Arcade', icon: '👾' },
  { id: 'idle', label: 'Build & Idle', icon: '🏗️' },
  { id: 'battle', label: 'Battle Bots', icon: '🤖' }
];

// controls: [{ keys: ['←', '→'], action: 'Steer' }, ...]  (shown on the play page)
window.GAMES = [
  { slug: 'rail-rush', title: 'Rail Rush', cats: ['running'], players: '1', color: '#ff7a1a', hot: true,
    blurb: 'Dash along the train tracks, dodge trains and grab every coin!',
    controls: [{ keys: ['←', '→'], action: 'Switch lanes' }, { keys: ['↑'], action: 'Jump' }, { keys: ['↓'], action: 'Slide' }] },
  { slug: 'neon-slope', title: 'Neon Slope', cats: ['running', 'arcade'], players: '1', color: '#22e3a1', hot: true,
    blurb: 'Roll down an endless neon slope. How far can you go?',
    controls: [{ keys: ['←', '→'], action: 'Steer' }] },
  { slug: 'tunnel-blitz', title: 'Tunnel Blitz', cats: ['running', 'arcade'], players: '1', color: '#b44dff',
    blurb: 'Blast through a spinning tunnel at crazy speed.',
    controls: [{ keys: ['←', '→'], action: 'Rotate' }] },
  { slug: 'beat-dash', title: 'Beat Dash', cats: ['running', 'arcade'], players: '1', color: '#00c2ff', hot: true,
    blurb: 'Jump to the beat over spikes and blocks. Can you beat every level?',
    controls: [{ keys: ['Space', 'Click'], action: 'Jump' }] },
  { slug: 'swing-hook', title: 'Swing Hook', cats: ['arcade'], players: '1', color: '#ff4fa3',
    blurb: 'Grab, swing and fling yourself to the finish line!',
    controls: [{ keys: ['Click', 'Space'], action: 'Hold to hook' }] },
  { slug: 'moto-madness', title: 'Moto Madness', cats: ['racing'], players: '1', color: '#ff3b3b', hot: true,
    blurb: 'Race your dirt bike over crazy ramps and pull off flips.',
    controls: [{ keys: ['↑'], action: 'Gas' }, { keys: ['↓'], action: 'Brake' }, { keys: ['←', '→'], action: 'Lean / flip' }] },
  { slug: 'drift-king', title: 'Drift King', cats: ['racing'], players: '1', color: '#ffc21a',
    blurb: 'One button. Endless drifting. Don\'t fall off the road!',
    controls: [{ keys: ['Space', 'Click'], action: 'Hold to turn' }] },
  { slug: 'fire-and-ice', title: 'Fire & Ice', cats: ['two-player', 'puzzle'], players: '1-2', color: '#ff5a1f', hot: true,
    blurb: 'Team up! Fire and Ice must work together to escape the temple.',
    controls: [{ keys: ['W', 'A', 'D'], action: 'Ice (jump / move)' }, { keys: ['↑', '←', '→'], action: 'Fire (jump / move)' }] },
  { slug: 'tank-splat', title: 'Paint Tanks', cats: ['two-player', 'battle'], players: '2-3', color: '#4caf50',
    blurb: 'Bounce paint balls around the maze and splat your friends!',
    controls: [{ keys: ['W', 'A', 'S', 'D', 'Q'], action: 'Green tank' }, { keys: ['↑', '←', '↓', '→', 'M'], action: 'Red tank' }] },
  { slug: 'sumo-bonk', title: 'Sumo Bonk', cats: ['two-player', 'sports'], players: '1-2', color: '#ff8fb1',
    blurb: 'Wobbly sumo showdown. Bonk your rival off the stage!',
    controls: [{ keys: ['W'], action: 'Player 1 jump' }, { keys: ['↑'], action: 'Player 2 jump' }] },
  { slug: 'air-hockey', title: 'Air Hockey Blast', cats: ['two-player', 'sports'], players: '1-2', color: '#00d1ff',
    blurb: 'Super fast air hockey against a friend or the computer.',
    controls: [{ keys: ['Mouse'], action: 'Move paddle (vs CPU)' }, { keys: ['W', 'A', 'S', 'D'], action: 'Player 1' }, { keys: ['↑', '←', '↓', '→'], action: 'Player 2' }] },
  { slug: 'hoop-heads', title: 'Hoop Heads', cats: ['sports', 'two-player'], players: '1-2', color: '#ff9f1c', hot: true,
    blurb: 'Big-head basketball! Dunk on the CPU or a friend.',
    controls: [{ keys: ['A', 'D', 'W'], action: 'Move / jump' }, { keys: ['S'], action: 'Shoot' }] },
  { slug: 'wacky-soccer', title: 'Wacky Soccer', cats: ['sports', 'two-player'], players: '1-2', color: '#2ecc71',
    blurb: 'Floppy one-button soccer. Pure chaos, pure goals.',
    controls: [{ keys: ['W'], action: 'Player 1 jump' }, { keys: ['↑'], action: 'Player 2 jump' }] },
  { slug: 'pool-party', title: 'Pool Party', cats: ['sports'], players: '1-2', color: '#1abc9c',
    blurb: 'Classic 8-ball pool. Line up your shot and sink them all.',
    controls: [{ keys: ['Mouse'], action: 'Aim' }, { keys: ['Drag'], action: 'Pull back to shoot' }] },
  { slug: 'critter-mart', title: 'Critter Mart', cats: ['idle'], players: '1', color: '#f4b400', hot: true,
    blurb: 'Run your own supermarket! Grow, stock, sell and get rich.',
    controls: [{ keys: ['W', 'A', 'S', 'D'], action: 'Walk' }] },
  { slug: 'pizza-clicker', title: 'Pizza Empire', cats: ['idle'], players: '1', color: '#ff6b35',
    blurb: 'Click pizzas, hire chefs and build a pizza empire.',
    controls: [{ keys: ['Click'], action: 'Make pizza' }] },
  { slug: 'block-world', title: 'Block World', cats: ['idle', 'arcade'], players: '1', color: '#5fbf3f', hot: true,
    blurb: 'Dig, build and explore a world made of blocks.',
    controls: [{ keys: ['A', 'D'], action: 'Walk' }, { keys: ['W', 'Space'], action: 'Jump' }, { keys: ['Click'], action: 'Mine' }, { keys: ['Right click'], action: 'Build' }] },
  { slug: 'block-burst', title: 'Block Burst', cats: ['puzzle'], players: '1', color: '#4f7cff',
    blurb: 'Drop blocks, clear lines, chain combos!',
    controls: [{ keys: ['Drag'], action: 'Place blocks' }] },
  { slug: 'merge-2048', title: '2048 Merge', cats: ['puzzle'], players: '1', color: '#edc22e',
    blurb: 'Slide and merge the tiles. Reach 2048!',
    controls: [{ keys: ['←', '↑', '→', '↓'], action: 'Slide tiles' }] },
  { slug: 'candy-rope', title: 'Munch Rope', cats: ['puzzle'], players: '1', color: '#8bd346',
    blurb: 'Cut the ropes and feed the hungry monster his candy.',
    controls: [{ keys: ['Swipe'], action: 'Cut ropes' }] },
  { slug: 'maze-dash', title: 'Maze Dash', cats: ['arcade'], players: '1', color: '#ffe600',
    blurb: 'Zoom through the maze, grab the dots, escape the rising goo!',
    controls: [{ keys: ['←', '↑', '→', '↓'], action: 'Dash' }] },
  { slug: 'road-hopper', title: 'Road Hopper', cats: ['arcade'], players: '1', color: '#7ed957', hot: true,
    blurb: 'Hop across busy roads and rivers. Don\'t get squished!',
    controls: [{ keys: ['↑', '←', '↓', '→'], action: 'Hop' }] },
  { slug: 'troll-level', title: 'Sneaky Levels', cats: ['arcade'], players: '1', color: '#ff4d6d',
    blurb: 'The level is out to get you. Expect the unexpected!',
    controls: [{ keys: ['←', '→'], action: 'Move' }, { keys: ['↑', 'Space'], action: 'Jump' }] },
  { slug: 'blob-battle', title: 'Blob Battle', cats: ['battle'], players: '1', color: '#36cfc9',
    blurb: 'Eat dots, grow huge and gobble up the bots.',
    controls: [{ keys: ['Mouse'], action: 'Move' }, { keys: ['Space'], action: 'Split' }] },
  { slug: 'paint-grab', title: 'Paint Grab', cats: ['battle'], players: '1', color: '#ff5ca8',
    blurb: 'Paint the map your color. Grab more land than the bots!',
    controls: [{ keys: ['←', '↑', '→', '↓'], action: 'Steer' }] },
  { slug: 'snake-arena', title: 'Snake Arena', cats: ['battle', 'arcade'], players: '1', color: '#8e44ff',
    blurb: 'Grow the longest snake in the arena. Trap the bots!',
    controls: [{ keys: ['Mouse'], action: 'Steer' }, { keys: ['Click'], action: 'Boost' }] }
];
