/* Emergency switch generated by tools/build.mjs --kill-sw: removes the offline cache. */
// Cache storage is shared by all deployments on this origin, including nested mounts.
var SCOPE = self.registration.scope;
// The separator must be escaped inside encoded scopes, including hyphenated child paths.
var CACHE_PREFIX = 'sg-v2-' + encodeURIComponent(SCOPE) + '|';
var OWN_FILES = ["favicon.svg","games/air-hockey/index.html","games/beat-dash/index.html","games/blob-battle/index.html","games/block-burst/index.html","games/block-world/index.html","games/candy-rope/index.html","games/critter-mart/index.html","games/drift-king/index.html","games/fire-and-ice/index.html","games/hoop-heads/index.html","games/maze-dash/index.html","games/merge-2048/index.html","games/moto-madness/index.html","games/neon-slope/index.html","games/paint-grab/index.html","games/pizza-clicker/index.html","games/pool-party/index.html","games/rail-rush/index.html","games/road-hopper/index.html","games/snake-arena/index.html","games/splat-strike/index.html","games/sumo-bonk/index.html","games/swing-hook/index.html","games/tank-splat/index.html","games/troll-level/index.html","games/tunnel-blitz/index.html","games/typing-test/index.html","games/wacky-soccer/index.html","icons/icon-192.png","icons/icon-512.png","icons/maskable-512.png","index.html","lib/three/three.min.js","manifest.webmanifest","shared/fonts/baloo-bhaijaan-2-arabic-500-normal.woff2","shared/fonts/baloo-bhaijaan-2-arabic-700-normal.woff2","shared/fonts/fredoka-latin-500-normal.woff2","shared/fonts/fredoka-latin-700-normal.woff2"];
function isLegacyCache(name) { return /^sg-[a-f0-9]{16}$/.test(name); }
async function cleanLegacyCaches(names) {
  // Unknown obsolete legacy URLs remain untouched because their owner is ambiguous.
  var urls = new Set(OWN_FILES.map(function (p) { return new URL(p, SCOPE).href; }));
  await Promise.all(names.filter(isLegacyCache).map(async function (name) {
    var cache = await caches.open(name);
    var requests = await cache.keys();
    await Promise.all(requests.filter(function (req) { return urls.has(req.url); })
      .map(function (req) { return cache.delete(req); }));
    if (!(await cache.keys()).length) await caches.delete(name);
  }));
}
self.addEventListener('install', function (event) { event.waitUntil(self.skipWaiting()); });
self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var names = await caches.keys();
    await Promise.all(names.filter(function (k) { return k.indexOf(CACHE_PREFIX) === 0; }).map(function (k) { return caches.delete(k); }));
    await cleanLegacyCaches(names);
    await self.registration.unregister();
    var list = await self.clients.matchAll({ type: 'window' });
    await Promise.all(list.map(function (c) { return c.navigate(c.url).catch(function () {}); }));
  })());
});
