/* Emergency switch generated by tools/build.mjs --kill-sw: removes the offline cache. */
self.addEventListener('install', function () { self.skipWaiting(); });
self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var names = await caches.keys();
    await Promise.all(names.filter(function (k) { return k.indexOf('sg-') === 0; }).map(function (k) { return caches.delete(k); }));
    await self.registration.unregister();
    var list = await self.clients.matchAll({ type: 'window' });
    list.forEach(function (c) { try { c.navigate(c.url); } catch (e) {} });
  })());
});
