/* Offline cache for ألعاب الفسحة. Generated by tools/build.mjs — do not edit. */
'use strict';
var VERSION = "6d73338bd036a030";
var FILES = {"favicon.svg":"fb11e07512b04ba5","games/air-hockey/index.html":"76a919587f4e0308","games/beat-dash/index.html":"7fbc84114f99a8b3","games/blob-battle/index.html":"70921d01baf9fa36","games/block-burst/index.html":"5a1dab2433135115","games/block-world/index.html":"6f74bb3ce2e4aa5e","games/candy-rope/index.html":"74b4e3d34a72239e","games/critter-mart/index.html":"213e972d3181669d","games/drift-king/index.html":"4daf70fc8fa3e4c1","games/fire-and-ice/index.html":"f404861c6026bca4","games/hoop-heads/index.html":"91a3e58e2f0cf2d7","games/maze-dash/index.html":"ffb8a297d9aa78b1","games/merge-2048/index.html":"f7f2ffd7f88abcf1","games/moto-madness/index.html":"faaffcd6acbd92c3","games/neon-slope/index.html":"8cb0c93cc50c6425","games/paint-grab/index.html":"de421d665d987894","games/pizza-clicker/index.html":"a2814c749164e605","games/pool-party/index.html":"957242ed26ea3922","games/rail-rush/index.html":"7e92ac5bcfb2791a","games/road-hopper/index.html":"9606c06a7bf45e49","games/snake-arena/index.html":"ca13e2cb5343d65b","games/splat-strike/index.html":"6e2b1aef18b1bbb3","games/sumo-bonk/index.html":"b00823380df77fc8","games/swing-hook/index.html":"aa8b402e529bd42c","games/tank-splat/index.html":"9b09382527c21f7a","games/troll-level/index.html":"0e21e97505c2cf2d","games/tunnel-blitz/index.html":"78abe08e62111be7","games/typing-test/index.html":"2979b36de17b5847","games/wacky-soccer/index.html":"83fe386e825e2d5d","icons/icon-192.png":"c3957eccb15853cd","icons/icon-512.png":"9961b8c241ac2ee5","icons/maskable-512.png":"b684fa0a23e03e9b","index.html":"196006cdc2a0dbb8","lib/three/three.min.js":"41b357e349452d53","manifest.webmanifest":"295dfb64f4c2e841","shared/fonts/baloo-bhaijaan-2-arabic-500-normal.woff2":"5f476ba56772e824","shared/fonts/baloo-bhaijaan-2-arabic-700-normal.woff2":"d14d2500adfe6d1e","shared/fonts/fredoka-latin-500-normal.woff2":"7d76e44a94b02894","shared/fonts/fredoka-latin-700-normal.woff2":"ee61b48acab42fcf"};
var CACHE = 'sg-' + VERSION;
var SCOPE = self.registration.scope;
var SCOPE_PATH = new URL(SCOPE).pathname;

function toRel(url) {
  var u = new URL(url);
  if (u.origin !== location.origin || u.pathname.indexOf(SCOPE_PATH) !== 0) return null;
  var p = decodeURIComponent(u.pathname.slice(SCOPE_PATH.length));
  if (p === '' || p.charAt(p.length - 1) === '/') p += 'index.html';
  return Object.prototype.hasOwnProperty.call(FILES, p) ? p : null;
}
function hex(buf) {
  return Array.prototype.map.call(new Uint8Array(buf), function (b) { return ('0' + b.toString(16)).slice(-2); }).join('');
}

// Install: keep unchanged files from the previous cache, download only the changed ones
// (straight from the network, checked against their hash), then take over right away.
self.addEventListener('install', function (event) {
  event.waitUntil((async function () {
    var cache = await caches.open(CACHE);
    var oldNames = (await caches.keys()).filter(function (k) { return k.indexOf('sg-') === 0 && k !== CACHE; });
    var olds = await Promise.all(oldNames.map(function (k) { return caches.open(k); }));
    var paths = Object.keys(FILES);
    var next = 0;
    async function one(p) {
      var url = new URL(p, SCOPE).href;
      if (await cache.match(url)) return;
      for (var i = 0; i < olds.length; i++) {
        var hit = await olds[i].match(url);
        if (hit && hit.headers.get('x-sg-hash') === FILES[p]) { await cache.put(url, hit); return; }
      }
      var res = await fetch(url + '?sg=' + FILES[p], { cache: 'no-store' });
      if (!res.ok) throw new Error('HTTP ' + res.status + ' ' + p);
      var body = await res.arrayBuffer();
      var got = hex(await crypto.subtle.digest('SHA-256', body)).slice(0, 16);
      if (got !== FILES[p]) throw new Error('stale copy of ' + p);
      var headers = new Headers(res.headers);
      headers.set('x-sg-hash', FILES[p]);
      await cache.put(url, new Response(body, { status: 200, headers: headers }));
    }
    async function worker() { while (next < paths.length) await one(paths[next++]); }
    try {
      await Promise.all([worker(), worker(), worker(), worker()]);
    } catch (e) {
      // Don't leave a half-filled cache on the disk; the current version keeps working and
      // the update is retried on the next visit.
      await caches.delete(CACHE);
      throw e;
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var names = await caches.keys();
    await Promise.all(names.filter(function (k) { return k.indexOf('sg-') === 0 && k !== CACHE; })
      .map(function (k) { return caches.delete(k); }));
    await self.clients.claim();
  })());
});

// Files of this version come from the offline cache; anything else goes to the network.
self.addEventListener('fetch', function (event) {
  var req = event.request;
  if (req.method !== 'GET') return;
  var rel = toRel(req.url);
  if (!rel) return;
  event.respondWith((async function () {
    var hit = await caches.match(new URL(rel, SCOPE).href, { cacheName: CACHE });
    if (hit) return hit;
    return fetch(req);
  })());
});
