#!/usr/bin/env node
// Deterministic build-size guardrails. The service worker is parsed as JSON data,
// never evaluated. Limits are reviewed source, never regenerated by this tool.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const FONT = /^[a-zA-Z0-9][a-zA-Z0-9._-]*\.(?:woff2?|ttf|otf|eot)$/;
const object = value => value !== null && typeof value === 'object' && !Array.isArray(value);

function validPath(file) {
  return typeof file === 'string' && file.split('/').every(part =>
    /^[a-zA-Z0-9._-]+$/.test(part) && part !== '.' && part !== '..');
}

// Check each component so a directory symlink cannot escape the build root.
// Reject all symlinks rather than trusting that today's target stays unchanged.
function assetPath(root, file, directory = false) {
  if (!validPath(file)) throw new Error('unsafe asset path: ' + file);
  let current = root;
  const parts = file.split('/');
  for (let i = 0; i < parts.length; i++) {
    current = path.join(current, parts[i]);
    const stat = fs.lstatSync(current);
    if (stat.isSymbolicLink()) throw new Error('symlink is not an asset: ' + file);
    const wantDirectory = i < parts.length - 1 || directory;
    if (wantDirectory ? !stat.isDirectory() : !stat.isFile()) {
      throw new Error('expected ' + (wantDirectory ? 'directory: ' : 'file: ') + file);
    }
  }
  return current;
}

function validateConfig(config) {
  const keys = ['format', 'portalBytes', 'teacherBytes', 'gameHtmlBytes', 'threeBytes', 'fontBytes', 'precacheBytes'];
  if (!object(config) || config.format !== 1 || Object.keys(config).length !== keys.length ||
      keys.some(key => !Object.hasOwn(config, key))) throw new Error('invalid budget config: expected format 1 and all documented keys');
  const budget = (value, label) => {
    if (!Number.isSafeInteger(value) || value <= 0) throw new Error('invalid positive finite integer byte limit: ' + label);
  };
  for (const key of ['portalBytes', 'teacherBytes', 'threeBytes', 'precacheBytes']) budget(config[key], key);
  for (const [key, pattern] of [['gameHtmlBytes', SLUG], ['fontBytes', FONT]]) {
    if (!object(config[key]) || !Object.keys(config[key]).length) throw new Error('invalid empty budget map: ' + key);
    for (const [name, value] of Object.entries(config[key])) {
      if (!pattern.test(name)) throw new Error('invalid asset name in ' + key + ': ' + name);
      budget(value, key + '.' + name);
    }
  }
}

function catalogSlugs(catalogPath) {
  // The existing source catalog is a plain script. Bound its evaluation; only
  // validated slug strings leave the context. No service-worker code runs here.
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(catalogPath, 'utf8'), sandbox,
    { timeout: 1000, contextCodeGeneration: { strings: false, wasm: false } });
  const games = sandbox.window.GAMES;
  if (!Array.isArray(games) || !games.length) throw new Error('catalog must contain a nonempty GAMES array');
  const slugs = games.map(game => game?.slug);
  if (slugs.some(slug => typeof slug !== 'string' || !SLUG.test(slug)) || new Set(slugs).size !== slugs.length) {
    throw new Error('catalog contains an invalid or duplicate game slug');
  }
  return slugs.sort();
}

function precacheFiles(source) {
  const matches = [...source.matchAll(/^var FILES = (.+);\r?$/gm)];
  if (matches.length !== 1) throw new Error('service worker must contain exactly one generated FILES JSON declaration');
  const manifest = JSON.parse(matches[0][1]);
  if (!object(manifest) || !Object.keys(manifest).length || JSON.stringify(manifest) !== matches[0][1]) {
    throw new Error('FILES must be a nonempty canonical JSON object (no duplicate keys)');
  }
  for (const [file, hash] of Object.entries(manifest)) {
    if (!validPath(file)) throw new Error('unsafe asset path in FILES: ' + file);
    if (typeof hash !== 'string' || !/^[a-f0-9]{16}$/.test(hash)) throw new Error('invalid FILES hash: ' + file);
  }
  return Object.keys(manifest).sort();
}

export function checkAssetBudgets({ root, configPath, catalogPath }) {
  const provenance = process.env.GITHUB_ACTIONS === 'true'
    ? { environment: 'github-actions', commit: process.env.GITHUB_SHA ?? null,
      repository: process.env.GITHUB_REPOSITORY ?? null, runId: process.env.GITHUB_RUN_ID ?? null,
      runAttempt: process.env.GITHUB_RUN_ATTEMPT ?? null }
    : { environment: 'local' };
  const report = { format: 1, unit: 'bytes', provenance, metrics: [], failures: [], passed: false };
  const fail = message => report.failures.push(message);
  try {
    const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    validateConfig(config);
    const slugs = catalogSlugs(catalogPath);
    root = path.resolve(root);
    const rootStat = fs.lstatSync(root);
    if (rootStat.isSymbolicLink() || !rootStat.isDirectory()) throw new Error('build root must be a real directory');
    root = fs.realpathSync(root);

    const compare = (actual, configured, label) => {
      for (const name of actual) if (!configured.includes(name)) fail(label + ' has no explicit budget: ' + name);
      for (const name of configured) if (!actual.includes(name)) fail(label + ' budget has no matching asset: ' + name);
    };
    compare(slugs, Object.keys(config.gameHtmlBytes).sort(), 'catalog game');
    const diskGames = fs.readdirSync(assetPath(root, 'games', true)).sort();
    compare(diskGames, slugs, 'built game');
    const diskFonts = fs.readdirSync(assetPath(root, 'shared/fonts', true)).filter(name => FONT.test(name)).sort();
    compare(diskFonts, Object.keys(config.fontBytes).sort(), 'font');

    const measure = (name, files, limitBytes) => {
      let bytes = 0;
      let complete = true;
      for (const file of files) {
        try { bytes += fs.statSync(assetPath(root, file)).size; }
        catch (error) { fail(name + ': cannot measure ' + file + ': ' + error.message); complete = false; }
      }
      if (!complete) bytes = null;
      const passed = complete && limitBytes !== null && bytes <= limitBytes;
      report.metrics.push({ name, files, bytes, limitBytes, passed });
      if (complete && limitBytes !== null && !passed) fail(name + ': ' + bytes + ' bytes exceeds limit ' + limitBytes + ' by ' + (bytes - limitBytes));
    };
    measure('portal', ['index.html'], config.portalBytes);
    measure('teacher', ['teacher.html'], config.teacherBytes);
    for (const slug of slugs) {
      // New games still get measured, but require an explicit reviewed limit.
      measure('game:' + slug, ['games/' + slug + '/index.html'], config.gameHtmlBytes[slug] ?? null);
    }
    measure('three.js', ['lib/three/three.min.js'], config.threeBytes);
    for (const name of [...new Set([...Object.keys(config.fontBytes), ...diskFonts])].sort()) {
      measure('font:' + name, ['shared/fonts/' + name], config.fontBytes[name] ?? null);
    }

    const files = precacheFiles(fs.readFileSync(assetPath(root, 'sw.js'), 'utf8'));
    const required = ['index.html', 'teacher.html', 'lib/three/three.min.js', ...slugs.map(slug => 'games/' + slug + '/index.html'),
      ...Object.keys(config.fontBytes).map(name => 'shared/fonts/' + name)];
    for (const file of required) if (!files.includes(file)) fail('required asset missing from FILES: ' + file);
    measure('offline-precache', files, config.precacheBytes);
  } catch (error) { fail(error.message); }
  report.passed = report.failures.length === 0;
  return report;
}

function main(args) {
  const options = { root: '_site', config: 'tools/asset-budgets.json' };
  const seen = new Set();
  for (let i = 0; i < args.length; i++) {
    const key = args[i].replace(/^--/, '');
    if (!['--root', '--config', '--report'].includes(args[i]) || seen.has(key) || !args[i + 1] || args[i + 1].startsWith('--')) {
      throw new Error('usage: node tools/asset-budgets.mjs [--root _site] [--config tools/asset-budgets.json] [--report artifacts/asset-budgets.json]');
    }
    seen.add(key);
    options[key] = args[++i];
  }
  const report = checkAssetBudgets({ root: path.resolve(REPO, options.root),
    configPath: path.resolve(REPO, options.config), catalogPath: path.join(REPO, 'js/catalog.js') });
  if (options.report) {
    const reportPath = path.resolve(REPO, options.report);
    fs.mkdirSync(path.dirname(reportPath), { recursive: true });
    fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  }
  for (const metric of report.metrics) console.log(`${metric.passed ? 'PASS' : 'FAIL'} ${metric.name}: ${metric.bytes ?? 'unavailable'} / ${metric.limitBytes ?? 'unconfigured'} bytes`);
  for (const failure of report.failures) console.error('FAIL ' + failure);
  console.log(`Asset budgets ${report.passed ? 'passed' : 'failed'}: ${report.metrics.length} measurements, ${report.failures.length} failures.`);
  if (!report.passed) process.exitCode = 1;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(process.argv.slice(2)); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
