#!/usr/bin/env node
/*
 * Builds the FAST version of the site into _site/ (published as a GitHub Pages artifact by
 * .github/workflows/build.yml on every push to main). The source files are unchanged and
 * still run as-is (locally, from a ZIP, or from main).
 *
 *   node tools/build.mjs [--out _site] [--no-minify] [--kill-sw]
 *
 * Why: the school PCs have slow hard disks. Every file is a separate disk read (and, after
 * GitHub's 10-minute cache expires, a separate check with the server), so the build cuts
 * the number of files a page needs:
 *   - each game becomes ONE html file: its CSS/JS plus shared/kit.js and shared/game.css are
 *     minified and inlined. Fonts and three.js stay shared files (cached once for all games).
 *   - the portal becomes one html file with its CSS, JS, the catalog and all thumbnails inlined.
 *   - sw.js: an offline cache. After the first visit the whole site is stored on the PC, pages
 *     open without asking the server, and it still works if the internet drops. Each build
 *     changes sw.js, so PCs download only the files that changed.
 *   - --kill-sw writes a sw.js that removes itself and its cache (emergency switch).
 *     The sw.js committed at the repo root is this same off switch, so switching GitHub Pages
 *     back to the plain source site also cleans the offline cache off every PC.
 *     (Regenerate it with: node tools/build.mjs --kill-sw --out _kill && cp _kill/sw.js sw.js)
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { svgDataUri } from './lib/svg-data-uri.mjs';

const require = createRequire(import.meta.url);
const ROOT = fs.realpathSync(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'));
const options = parseArgs(process.argv.slice(2));
const DEST = path.resolve(ROOT, options.out);
const MINIFY = options.minify;
const KILL_SW = options.killSW;
const esbuild = MINIFY ? require('esbuild') : null;

const posix = p => p.split(path.sep).join('/');
const read = p => fs.readFileSync(p, 'utf8');
const hash = buf => crypto.createHash('sha256').update(buf).digest('hex').slice(0, 16);
const isLocal = u => !/^(?:[a-z]+:|\/\/|#|\/)/i.test(u);

const OUTPUT_MARKER = '.school-games-build.json';
const OUTPUT_PRODUCER = 'school-games/tools/build.mjs';
const SOURCE_DIRS = new Set(['.git', '.github', '.agents', '.aws', '.codex', 'games', 'js', 'css', 'shared', 'lib', 'icons', 'tools', 'docs', 'node_modules', 'multiplayer-server']);
const filesystemName = name => process.platform === 'win32' ? name.toLowerCase() : name;

function parseArgs(args) {
  const result = { out: '_site', minify: true, killSW: false };
  let hasOut = false;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--out') {
      if (hasOut) throw new Error('--out may only be specified once');
      const value = args[++i];
      if (!value || !value.trim() || value.startsWith('--')) throw new Error('--out requires a directory path');
      result.out = value;
      hasOut = true;
    } else if (args[i] === '--no-minify') result.minify = false;
    else if (args[i] === '--kill-sw') result.killSW = true;
    else throw new Error('unknown build argument: ' + args[i]);
  }
  return result;
}

function isWithin(parent, child) {
  const rel = path.relative(parent, child);
  return rel === '' || (rel !== '..' && !rel.startsWith('..' + path.sep) && !path.isAbsolute(rel));
}

function validOutputFile(file) {
  return typeof file === 'string' && file.length > 0 && !file.includes('\\') &&
    file.split('/').every(part => part && part !== '.' && part !== '..' && filesystemName(part) !== '.git') &&
    !path.isAbsolute(file);
}

// Record files and empty directories without following links. A generated folder
// must never become a way to remove somebody else's linked or newly added files.
function outputTree(dir, rel = '', result = { files: [], dirs: [] }) {
  for (const entry of fs.readdirSync(path.join(dir, rel), { withFileTypes: true })) {
    const file = rel ? rel + '/' + entry.name : entry.name;
    if (filesystemName(entry.name) === '.git' || entry.isSymbolicLink()) throw new Error('refusing output containing a Git repository or symlink: ' + file);
    if (entry.isDirectory()) { result.dirs.push(file); outputTree(dir, file, result); }
    else if (entry.isFile()) result.files.push(file);
    else throw new Error('refusing output containing a special file: ' + file);
  }
  return result;
}

function legacyOutputFiles(dir, actualFiles) {
  const worker = read(path.join(dir, 'sw.js'));
  const emergency = worker.startsWith('/* Emergency switch generated by tools/build.mjs --kill-sw: removes the offline cache. */');
  if (!worker.startsWith('/* Offline cache for ألعاب الفسحة. Generated by tools/build.mjs — do not edit. */') && !emergency) return null;
  const match = worker.match(/^var (?:FILES|OWN_FILES) = (.+);$/m);
  if (!match) {
    // The original emergency switch had no file manifest. Its generated artifact
    // still has a narrowly defined layout; unrelated files must continue to block replacement.
    if (!emergency || !worker.includes('self.registration.unregister()')) return null;
    const originalAsset = /^(?:index\.html|sw\.js|\.nojekyll|favicon\.svg|manifest\.webmanifest|games\/[^/]+\/(?:index\.html|thumb\.svg)|lib\/three\/(?:three\.min\.js|LICENSE)|shared\/fonts\/[^/]+|icons\/[^/]+)$/;
    return new Set(actualFiles.filter(file => originalAsset.test(file)));
  }
  const manifest = JSON.parse(match[1]);
  const files = Array.isArray(manifest) ? manifest : Object.keys(manifest);
  if (!files.includes('index.html') || !files.every(validOutputFile)) return null;
  const allowed = new Set([...files, 'sw.js', '.nojekyll']);
  for (const file of files) {
    if (/^games\/[^/]+\/index\.html$/.test(file)) allowed.add(file.replace(/index\.html$/, 'thumb.svg'));
  }
  return allowed;
}

function verifyGeneratedOutput(dir, tree) {
  let allowed;
  if (tree.files.includes(OUTPUT_MARKER)) {
    const marker = JSON.parse(read(path.join(dir, OUTPUT_MARKER)));
    if (marker.producer !== OUTPUT_PRODUCER || marker.format !== 1 || !Array.isArray(marker.files) ||
        !marker.files.includes('index.html') || !marker.files.includes('sw.js') || !marker.files.every(validOutputFile)) {
      throw new Error('invalid generated-output marker');
    }
    allowed = new Set([...marker.files, OUTPUT_MARKER]);
  } else {
    if (!['index.html', 'sw.js', '.nojekyll'].every(file => tree.files.includes(file))) throw new Error('no generated-output marker');
    allowed = legacyOutputFiles(dir, tree.files);
    if (!allowed) throw new Error('unrecognized legacy output');
    // The original builder copied these licenses but deliberately did not precache them.
    for (const file of tree.files) if (/^(?:lib\/three\/LICENSE|shared\/fonts\/LICENSE[^/]*)$/.test(file)) allowed.add(file);
  }
  for (const file of tree.files) if (!allowed.has(file)) throw new Error('output contains an unrecognized file: ' + file);
  for (const dir of tree.dirs) if (![...allowed].some(file => file.startsWith(dir + '/'))) throw new Error('output contains an unrecognized directory: ' + dir);
}

function validateOutput() {
  if (DEST === ROOT || !isWithin(ROOT, DEST)) throw new Error('refusing to write at or outside the repo root: ' + DEST);
  const parts = path.relative(ROOT, DEST).split(path.sep);
  if (SOURCE_DIRS.has(filesystemName(parts[0])) || parts.some(part => filesystemName(part) === '.git')) throw new Error('refusing a source or protected output directory: ' + DEST);
  let current = ROOT;
  for (const part of parts) {
    current = path.join(current, part);
    let stat;
    try { stat = fs.lstatSync(current); } catch (error) { if (error.code === 'ENOENT') break; throw error; }
    if (stat.isSymbolicLink()) throw new Error('refusing a symlink in the output path: ' + current);
    if (!stat.isDirectory()) throw new Error('output path is not a directory: ' + current);
  }
  if (fs.existsSync(path.join(ROOT, '.git'))) {
    let tracked;
    try { tracked = execFileSync('git', ['-C', ROOT, 'ls-files', '-z'], { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 }).split('\0').filter(Boolean); }
    catch (error) { throw new Error('cannot verify tracked files before replacing output', { cause: error }); }
    if (tracked.some(file => isWithin(DEST, path.resolve(ROOT, file)))) throw new Error('refusing output containing tracked repository files: ' + DEST);
  }
  if (fs.existsSync(DEST)) {
    const tree = outputTree(DEST);
    if (tree.files.length || tree.dirs.length) {
      try { verifyGeneratedOutput(DEST, tree); }
      catch (error) { throw new Error('refusing to replace non-generated output ' + DEST + ': ' + error.message + '. Choose a new or empty output directory.'); }
    }
  }
}

function publishOutput() {
  // Recheck after building: the destination may have changed while files were generated.
  validateOutput();
  let backup;
  if (fs.existsSync(DEST)) {
    backup = fs.mkdtempSync(path.join(path.dirname(DEST), '.school-games-backup-'));
    fs.rmdirSync(backup);
    fs.renameSync(DEST, backup);
  }
  try { fs.renameSync(OUT, DEST); }
  catch (error) {
    if (backup) {
      try {
        if (fs.existsSync(DEST)) throw new Error('the output destination was recreated during publication');
        fs.renameSync(backup, DEST);
      } catch (restoreError) {
        throw new AggregateError([error, restoreError], 'could not publish output; the previous build is preserved at ' + backup);
      }
    }
    throw error;
  }
  if (backup) fs.rmSync(backup, { recursive: true, force: true });
}

validateOutput();
fs.mkdirSync(path.dirname(DEST), { recursive: true });
const OUT = fs.mkdtempSync(path.join(path.dirname(DEST), '.school-games-build-'));

function write(rel, data) {
  const p = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, data);
}
function copy(rel) { write(rel, fs.readFileSync(path.join(ROOT, rel))); }

/* ------------------------------------------------------------- minify */
const jsCache = new Map();
function jsFor(file) {
  if (jsCache.has(file)) return jsCache.get(file);
  let code = read(file);
  if (MINIFY) {
    // Plain scripts: esbuild keeps top-level names (games share globals between files)
    // and only shortens local names.
    code = esbuild.transformSync(code, { loader: 'js', minify: true, target: 'chrome100', legalComments: 'none', charset: 'utf8' }).code;
  }
  // Keep the inline <script> from being closed or confused by the HTML parser.
  code = code.replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--');
  jsCache.set(file, code);
  return code;
}
function cssFor(file, htmlDir) {
  let css = read(file);
  css = css.replace(/url\(\s*(['"]?)([^'")]+)\1\s*\)/g, (m, q, u) => {
    if (!isLocal(u)) return m;
    const abs = path.resolve(path.dirname(file), u);
    return 'url(' + q + posix(path.relative(htmlDir, abs)) + q + ')';
  });
  if (MINIFY) css = esbuild.transformSync(css, { loader: 'css', minify: true, target: 'chrome100', charset: 'utf8' }).code.trim();
  return css.replace(/<\/(style)/gi, '<\\/$1');
}

/* Inline every local stylesheet and script of an html page (except three.js). */
function inlinePage(htmlFile, extra) {
  const dir = path.dirname(htmlFile);
  let html = read(htmlFile);
  html = html.replace(/<link\b[^>]*>/gi, tag => {
    if (!/\brel="stylesheet"/i.test(tag)) return tag;
    const href = (tag.match(/\bhref="([^"]+)"/i) || [])[1];
    if (!href || !isLocal(href)) return tag;
    return '<style>' + cssFor(path.resolve(dir, href), dir) + '</style>';
  });
  html = html.replace(/<script\b([^>]*)>\s*<\/script>/gi, (tag, attrs) => {
    const src = (attrs.match(/\bsrc="([^"]+)"/i) || [])[1];
    if (!src || !isLocal(src) || /(^|\/)lib\/three\//.test(src)) return tag;
    if (extra && extra.skip && extra.skip.includes(src)) return '';
    if (attrs.replace(/\bsrc="[^"]+"/i, '').trim()) throw new Error(`${htmlFile}: unsupported script attributes: ${tag}`);
    let code = jsFor(path.resolve(dir, src));
    if (extra && extra.before && extra.before[src]) code = extra.before[src] + '\n' + code;
    return '<script>' + code + '</script>';
  });
  const left = html.match(/<script\b[^>]*\bsrc="(?!(?:\.\.\/)*lib\/three\/)[^"]+"/gi);
  if (left) throw new Error(`${htmlFile}: scripts left un-inlined: ${left.join(', ')}`);
  return html;
}

/* --------------------------------------------------------------- games */
try {
  const cat = { window: {} };
  vm.runInNewContext(read(path.join(ROOT, 'js/catalog.js')), cat);
  const catalogSlugs = cat.window.GAMES.map(g => g.slug);
  const gameDirs = fs.readdirSync(path.join(ROOT, 'games')).filter(d => fs.existsSync(path.join(ROOT, 'games', d, 'index.html')));
  const report = [];
  for (const slug of gameDirs) {
    const html = inlinePage(path.join(ROOT, 'games', slug, 'index.html'));
    write(`games/${slug}/index.html`, html);
    report.push([`games/${slug}/index.html`, Buffer.byteLength(html)]);
  }
  const missing = catalogSlugs.filter(s => !gameDirs.includes(s));
  if (missing.length) console.warn('warning: catalog games without a folder:', missing.join(', '));

  /* -------------------------------------------------------------- portal */
  const thumbs = {};
  for (const slug of gameDirs) {
    const f = path.join(ROOT, 'games', slug, 'thumb.svg');
    if (fs.existsSync(f)) thumbs[slug] = svgDataUri(read(f));
  }
  let portal = inlinePage(path.join(ROOT, 'index.html'), {
    before: {
      'js/site.js': 'window.SG_THUMBS=' + JSON.stringify(thumbs).replace(/<\//g, '<\\/') + ';',
      'js/offline.js': 'window.SG_OFFLINE_BUILD=true;'
    },
    skip: KILL_SW ? ['js/offline.js'] : []
  });
  // A kill-switch deployment omits the registering controller completely.
  write('index.html', portal);
  report.unshift(['index.html', Buffer.byteLength(portal)]);

  /* --------------------------------------------------------- static files */
  const statics = ['favicon.svg', 'manifest.webmanifest', 'lib/three/three.min.js', 'lib/three/LICENSE'];
  for (const f of fs.readdirSync(path.join(ROOT, 'shared/fonts'))) statics.push('shared/fonts/' + f);
  if (fs.existsSync(path.join(ROOT, 'icons'))) for (const f of fs.readdirSync(path.join(ROOT, 'icons'))) statics.push('icons/' + f);
  for (const f of statics) if (fs.existsSync(path.join(ROOT, f))) copy(f);
  write('.nojekyll', '');

  /* ------------------------------------------------------ service worker */
  // Everything a visit can need, with content hashes. Thumbnail SVGs exist only
  // inside the portal in the release; the editable sources retain separate files.
  const precache = {};
  (function walk(dir) {
    for (const e of fs.readdirSync(path.join(OUT, dir), { withFileTypes: true })) {
      const rel = dir ? dir + '/' + e.name : e.name;
      if (e.isDirectory()) { walk(rel); continue; }
      if (/(^|\/)(LICENSE[^/]*|\.nojekyll)$/.test(rel)) continue;
      precache[rel] = hash(fs.readFileSync(path.join(OUT, rel)));
    }
  })('');
  const version = hash(JSON.stringify(precache));
  const sw = KILL_SW ? KILL_SW_SOURCE(Object.keys(precache)) : SW_SOURCE(version, precache);
  write('sw.js', sw);
  // This inventory proves ownership on the next build. Write it after precaching so
  // development bookkeeping never becomes part of the offline site's file list.
  write(OUTPUT_MARKER, JSON.stringify({ producer: OUTPUT_PRODUCER, format: 1, files: outputTree(OUT).files.sort() }, null, 2) + '\n');

  /* -------------------------------------------------------------- report */
  const total = Object.keys(precache).reduce((a, f) => a + fs.statSync(path.join(OUT, f)).size, 0);
  publishOutput();
  console.log(`built ${gameDirs.length} games + portal into ${posix(path.relative(ROOT, DEST))}/ (minify ${MINIFY ? 'on' : 'off'})`);
  console.log(`offline cache: ${Object.keys(precache).length} files, ${(total / 1048576).toFixed(2)} MB, version ${version}${KILL_SW ? ' (KILL SWITCH sw.js)' : ''}`);
  for (const [f, b] of report.slice(0, 1)) console.log(`  ${f}: ${(b / 1024).toFixed(0)} KB`);
  const gb = report.slice(1).map(r => r[1]);
  console.log(`  games: ${(Math.min(...gb) / 1024).toFixed(0)}–${(Math.max(...gb) / 1024).toFixed(0)} KB each (one file per game)`);
} finally {
  fs.rmSync(OUT, { recursive: true, force: true });
}

function SW_SOURCE(VERSION, FILES) {
  return `/* Offline cache for ألعاب الفسحة. Generated by tools/build.mjs — do not edit. */
'use strict';
var VERSION = ${JSON.stringify(VERSION)};
var FILES = ${JSON.stringify(FILES)};
${CACHE_SCOPE_SOURCE(Object.keys(FILES))}
var CACHE = CACHE_PREFIX + VERSION;
var SCOPE_PATH = new URL(SCOPE).pathname;

function toRel(url) {
  var u = new URL(url);
  if (u.origin !== location.origin || u.pathname.indexOf(SCOPE_PATH) !== 0) return null;
  var p = decodeURIComponent(u.pathname.slice(SCOPE_PATH.length));
  if (p === '' || p.charAt(p.length - 1) === '/') p += 'index.html';
  return Object.prototype.hasOwnProperty.call(FILES, p) ? p : null;
}
function hex(buf) {
  return Array.prototype.map.call(new Uint8Array(buf), function (b) { return ('0' + b.toString(16)).slice(-2); }).join('');
}
async function fetchVerified(p) {
  var url = new URL(p, SCOPE).href;
  var res = await fetch(url + '?sg=' + FILES[p], { cache: 'no-store' });
  if (!res.ok) throw new Error('HTTP ' + res.status + ' ' + p);
  var body = await res.arrayBuffer();
  var got = hex(await crypto.subtle.digest('SHA-256', body)).slice(0, 16);
  if (got !== FILES[p]) throw new Error('stale copy of ' + p);
  var headers = new Headers(res.headers);
  headers.set('x-sg-hash', FILES[p]);
  return new Response(body, { status: 200, headers: headers });
}

// Report only a fully verified copy of this worker's version. Cache eviction or
// damaged entries must never leave the portal claiming that all games are ready.
var checkingStatus = null;
async function offlineStatus(repair) {
  if (checkingStatus) await checkingStatus;
  var task = (async function () {
    var paths = Object.keys(FILES), count = 0;
    if (!(await caches.has(CACHE)) && !repair) return { ready: false, count: 0, total: paths.length, version: VERSION };
    var cache = await caches.open(CACHE), next = 0;
    async function inspect() {
      while (next < paths.length) {
        var p = paths[next++], url = new URL(p, SCOPE).href;
        var hit = await cache.match(url), valid = false;
        if (hit && hit.headers.get('x-sg-hash') === FILES[p]) {
          valid = hex(await crypto.subtle.digest('SHA-256', await hit.arrayBuffer())).slice(0, 16) === FILES[p];
        }
        if (!valid && repair) {
          try { await cache.put(url, await fetchVerified(p)); valid = true; }
          catch (e) { /* Keep the old verified version; a new worker may be needed. */ }
        }
        if (valid) count++;
      }
    }
    await Promise.all([inspect(), inspect(), inspect(), inspect()]);
    if (repair && count !== paths.length) self.registration.update().catch(function () {});
    // A handle can survive deletion from CacheStorage while hashing its bodies.
    var present = await caches.has(CACHE);
    return { ready: present && count === paths.length, count: present ? count : 0, total: paths.length, version: VERSION };
  })();
  checkingStatus = task.catch(function () {});
  try { return await task; } finally { checkingStatus = null; }
}
self.addEventListener('message', function (event) {
  var data = event.data, port = event.ports && event.ports[0];
  if (!data || data.type !== 'sg:offline-status' || !port) return;
  if (!event.source || toRel(event.source.url) !== 'index.html') return;
  event.waitUntil(offlineStatus(data.repair === true).then(function (result) {
    result.type = 'sg:offline-status'; result.id = data.id; port.postMessage(result);
  }).catch(function () {
    port.postMessage({ type: 'sg:offline-status', id: data.id, ready: false, count: 0, total: Object.keys(FILES).length, version: VERSION });
  }));
});

// CacheStorage can be cleared while this worker stays registered. An unchanged
// worker will not install again, so a miss also repairs the other missing files.
// Keep verified entries if repair is interrupted; a later miss can retry it.
var repairing = null;
function repairCache(cache) {
  if (repairing) return repairing;
  var paths = Object.keys(FILES), next = 0;
  async function worker() {
    while (next < paths.length) {
      var p = paths[next++], url = new URL(p, SCOPE).href;
      if (!(await cache.match(url))) await cache.put(url, await fetchVerified(p));
    }
  }
  // Wait for every worker before ending the event, even if one fetch fails.
  repairing = Promise.allSettled([worker(), worker(), worker(), worker()]).then(function (results) {
    // The server may have moved on and no longer have this version's bytes.
    // Ask for its new worker instead of mixing those bytes into this cache.
    if (results.some(function (result) { return result.status === 'rejected'; })) {
      return self.registration.update().catch(function () {});
    }
  }).then(function () {
    repairing = null;
  });
  return repairing;
}

// Install: keep unchanged files from the previous cache, download only the changed ones
// (straight from the network, checked against their hash), then take over right away.
self.addEventListener('install', function (event) {
  event.waitUntil((async function () {
    var cache = await caches.open(CACHE);
    var oldNames = (await caches.keys()).filter(function (k) { return (k.indexOf(CACHE_PREFIX) === 0 || isLegacyCache(k)) && k !== CACHE; });
    var olds = await Promise.all(oldNames.map(function (k) { return caches.open(k); }));
    var paths = Object.keys(FILES);
    var next = 0;
    async function one(p) {
      var url = new URL(p, SCOPE).href;
      if (await cache.match(url)) return;
      for (var i = 0; i < olds.length; i++) {
        var hit = await olds[i].match(url);
        if (hit && hit.headers.get('x-sg-hash') === FILES[p]) {
          var oldHash = hex(await crypto.subtle.digest('SHA-256', await hit.clone().arrayBuffer())).slice(0, 16);
          if (oldHash === FILES[p]) { await cache.put(url, hit); return; }
        }
      }
      await cache.put(url, await fetchVerified(p));
    }
    async function worker() { while (next < paths.length) await one(paths[next++]); }
    try {
      await Promise.all([worker(), worker(), worker(), worker()]);
    } catch (e) {
      // Don't leave a half-filled cache on the disk; the current version keeps working and
      // the update is retried on the next visit.
      await caches.delete(CACHE);
      throw e;
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var names = await caches.keys();
    await Promise.all(names.filter(function (k) { return k.indexOf(CACHE_PREFIX) === 0 && k !== CACHE; })
      .map(function (k) { return caches.delete(k); }));
    await cleanLegacyCaches(names);
    await self.clients.claim();
  })());
});

// Files of this version come from the offline cache; anything else goes to the network.
self.addEventListener('fetch', function (event) {
  var req = event.request;
  if (req.method !== 'GET') return;
  var rel = toRel(req.url);
  if (!rel) return;
  var repairTarget;
  var response = (async function () {
    var url = new URL(rel, SCOPE).href;
    // Hold the cache handle before fetching: if an update deletes this version
    // during recovery, late writes must not reopen its obsolete cache by name.
    var cache = await caches.open(CACHE);
    var hit = await cache.match(url);
    if (hit) return hit;
    // Never put newer or stale network bytes into the active version's cache.
    var res = await fetchVerified(rel);
    repairTarget = cache;
    try { await repairTarget.put(url, res.clone()); } catch (e) { /* storage may be full */ }
    return res;
  })();
  event.respondWith(response);
  // Respond as soon as the requested file is verified; keep repairing the rest
  // in the background so the next offline visit includes unvisited games too.
  event.waitUntil(response.then(function () {
    if (repairTarget) return repairCache(repairTarget);
  }).catch(function () {
    // A rejected old-version navigation may never reach the portal's register
    // call. Check for a replacement here so the next reload can recover too.
    return self.registration.update().catch(function () {});
  }));
});
`;
}

// Legacy caches were shared by every mount on an origin. Only remove exact file URLs
// belonging to this build; prefix matching would also remove nested deployments.
// Obsolete, unknown legacy files are deliberately left alone rather than risking
// another deployment's data. New caches have an unambiguous scope namespace.
function CACHE_SCOPE_SOURCE(files) {
  return `// Cache storage is shared by all deployments on this origin, including nested mounts.
var SCOPE = self.registration.scope;
// The separator must be escaped inside encoded scopes, including hyphenated child paths.
var CACHE_PREFIX = 'sg-v2-' + encodeURIComponent(SCOPE) + '|';
var OWN_FILES = ${JSON.stringify(files)};
function isLegacyCache(name) { return /^sg-[a-f0-9]{16}$/.test(name); }
async function cleanLegacyCaches(names) {
  // Unknown obsolete legacy URLs remain untouched because their owner is ambiguous.
  var urls = new Set(OWN_FILES.map(function (p) { return new URL(p, SCOPE).href; }));
  await Promise.all(names.filter(isLegacyCache).map(async function (name) {
    var cache = await caches.open(name);
    var requests = await cache.keys();
    await Promise.all(requests.filter(function (req) { return urls.has(req.url); })
      .map(function (req) { return cache.delete(req); }));
    if (!(await cache.keys()).length) await caches.delete(name);
  }));
}`;
}

function KILL_SW_SOURCE(files) {
  return `/* Emergency switch generated by tools/build.mjs --kill-sw: removes the offline cache. */
${CACHE_SCOPE_SOURCE(files)}
self.addEventListener('install', function (event) { event.waitUntil(self.skipWaiting()); });
self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var names = await caches.keys();
    await Promise.all(names.filter(function (k) { return k.indexOf(CACHE_PREFIX) === 0; }).map(function (k) { return caches.delete(k); }));
    await cleanLegacyCaches(names);
    await self.registration.unregister();
    var list = await self.clients.matchAll({ type: 'window' });
    await Promise.all(list.map(function (c) { return c.navigate(c.url).catch(function () {}); }));
  })());
});
`;
}
