/* Recorded solutions for every Munch Rope level: [frame, action, arg].
 * Generated by dev/solve.js and checked by dev/verify.js. The game uses the
 * plans for its hint (order and timing) and its "watch the solution" demo. */
(function (root) {
  var S = [
    /* 1 */ [[10,"cut","p0"]],
    /* 2 */ [[94,"cut","p0"]],
    /* 3 */ [[10,"cut","p0"],[89,"cut","p1"]],
    /* 4 */ [[10,"cut","p2"],[88,"cut","p0"],[258,"cut","p1"]],
    /* 5 */ [[10,"cut","p0"],[226,"cut","p1"]],
    /* 6 */ [[10,"cut","p0"],[85,"cut","g0"]],
    /* 7 */ [[10,"cut","p0"],[71,"cut","g0"],[121,"cut","g1"]],
    /* 8 */ [[10,"cut","p0"],[10,"cut","p1"]],
    /* 9 */ [[95,"pop"],[129,"cut","p0"]],
    /* 10 */ [[10,"cut","p0"],[12,"cut","p1"],[239,"pop"],[459,"cut","g0"]],
    /* 11 */ [[165,"cut","p0"]],
    /* 12 */ [[259,"cut","p0"]],
    /* 13 */ [[165,"cut","p0"],[446,"cut","g0"],[517,"cut","g1"]],
    /* 14 */ [[10,"cut","p0"],[280,"pop"],[338,"cut","g0"]],
    /* 15 */ [[10,"cut","p0"],[182,"cut","p1"],[266,"cut","g0"]],
    /* 16 */ [[10,"cut","p0"],[77,"puff",0]],
    /* 17 */ [[10,"puff",0],[20,"cut","p0"]],
    /* 18 */ [[10,"cut","p0"]],
    /* 19 */ [[154,"cut","p0"]],
    /* 20 */ [[72,"cut","p0"]],
    /* 21 */ [[10,"cut","p0"],[74,"puff",0],[93,"puff",0],[228,"pop"],[357,"cut","g0"]],
    /* 22 */ [[131,"cut","p0"]],
    /* 23 */ [[10,"cut","p0"],[60,"puff",0],[81,"puff",0],[98,"puff",0]],
    /* 24 */ [[39,"cut","p0"],[95,"cut","p1"]],
    /* 25 */ [[93,"cut","p0"]],
    /* 26 */ [[10,"cut","p1"],[12,"cut","p0"],[54,"puff",0],[152,"puff",0],[327,"pop"]],
    /* 27 */ [[257,"cut","p0"],[313,"cut","g0"]],
    /* 28 */ [[84,"cut","p0"],[218,"puff",0],[238,"puff",0]],
    /* 29 */ [[12,"cut","p0"],[167,"cut","g0"],[316,"cut","g1"],[386,"cut","g2"]],
    /* 30 */ [[10,"cut","p0"],[64,"cut","p1"],[137,"cut","g0"]]
  ];
  root.MUNCH_SOLUTIONS = S;
  if (typeof module !== 'undefined' && module.exports) module.exports = S;
})(typeof window !== 'undefined' ? window : globalThis);
