/* Recorded solutions for every Munch Rope level: [frame, action, arg].
 * Generated by dev/solve.js and checked by dev/verify.js. The game uses the
 * order of actions for its hint button. */
(function (root) {
  var S = [
    /* 1 */ [[14,"cut","p0"]],
    /* 2 */ [[93,"cut","p0"]],
    /* 3 */ [[22,"cut","p0"],[101,"cut","p1"]],
    /* 4 */ [[0,"cut","p0"],[82,"cut","p2"],[160,"cut","p1"]],
    /* 5 */ [[75,"cut","p0"],[289,"cut","p1"]],
    /* 6 */ [[5,"cut","p0"],[222,"cut","g0"]],
    /* 7 */ [[4,"cut","p0"],[66,"cut","g0"],[120,"cut","g1"]],
    /* 8 */ [[0,"cut","p0"],[0,"cut","p1"]],
    /* 9 */ [[128,"pop"],[161,"cut","p0"]],
    /* 10 */ [[31,"cut","p1"],[114,"cut","p0"],[363,"pop"],[433,"cut","g0"]],
    /* 11 */ [[165,"cut","p0"]],
    /* 12 */ [[264,"cut","p0"]],
    /* 13 */ [[170,"cut","p0"],[424,"cut","g0"],[487,"cut","g1"]],
    /* 14 */ [[83,"cut","p0"],[339,"pop"],[397,"cut","g0"]],
    /* 15 */ [[41,"cut","p0"],[89,"cut","p1"],[316,"cut","g0"]],
    /* 16 */ [[2,"cut","p0"],[69,"puff",0]],
    /* 17 */ [[28,"puff",0],[40,"cut","p0"]],
    /* 18 */ [[3,"cut","p0"]],
    /* 19 */ [[157,"cut","p0"]],
    /* 20 */ [[75,"cut","p0"]],
    /* 21 */ [[0,"cut","p0"],[52,"puff",0],[73,"puff",0],[233,"pop"],[296,"puff",0],[310,"puff",0],[331,"cut","g0"]],
    /* 22 */ [[133,"cut","p0"]],
    /* 23 */ [[33,"cut","p0"],[86,"puff",0],[97,"puff",0],[110,"puff",0]],
    /* 24 */ [[34,"cut","p0"],[104,"cut","p1"]],
    /* 25 */ [[240,"cut","p0"]],
    /* 26 */ [[25,"cut","p0"],[27,"cut","p1"],[128,"puff",0],[153,"puff",0],[218,"pop"]],
    /* 27 */ [[259,"cut","p0"],[308,"cut","g0"]],
    /* 28 */ [[81,"cut","p0"],[211,"puff",0],[262,"puff",0]],
    /* 29 */ [[9,"cut","p0"],[153,"cut","g0"],[191,"cut","g1"]],
    /* 30 */ [[36,"cut","p0"],[90,"cut","p1"],[163,"cut","g0"]]
  ];
  root.MUNCH_SOLUTIONS = S;
  if (typeof module !== 'undefined' && module.exports) module.exports = S;
})(typeof window !== 'undefined' ? window : globalThis);
